baseURL = "https://www.disnetdev.com/"
languageCode = "en-us"
title = "disnetdev"
theme = "light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Tim Disney"

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  url = "/blog"

[[menu.main]]
  identifier = "micro"
  name = "micro"
  url = "/micro"

[[menu.main]]
  identifier = "papers"
  name = "papers"
  url = "/papers"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
